### ISSUE TITLE
Comment upload nos fichiers ?

### ISSUE THREAD

**Issue by chatOpastel** [gaetanHerve/pratique-de-la-programmation#15]
Salut Gaetan, comment vas-tu ?

Je n'arrive pas à upload le dossier .zip de notre projet sur l'espace de rendu. 
Je suis sûr que ce n'est pas très sorcier en plus.

Passe de bonnes fêtes, à plus !

Paulin

**Comment by gaetanHerve** [comment]
Bonjour Paulin,

Très bien, et toi ?
Je me permets de clore cette issue. J'ai vu que tu as bien déposé votre projet dans #16 

Bonne fin d'année,
Gaëtan
